### ISSUE TITLE
Default.py was failing in IMU reset

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#25]
I was getting the errors below and could not get anything that used the differential_drive to work. I finally had to unplug and replug in the XRP to get the errors to go away.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/lib/XRPLib/defaults.py", line 19, in <module>
  File "/lib/XRPLib/imu.py", line 41, in get_default_imu
  File "/lib/XRPLib/imu.py", line 60, in __init__
  File "/lib/XRPLib/imu.py", line 100, in _setreg
OSError: [Errno 110] ETIMEDOUT
```

**Comment by Kreeevin** [comment]
I think this is fixed in v1.0.0
